### ISSUE TITLE
error: narrowing conversion of '138' from 'int' to 'char' inside { } [-Wnarrowing]

### ISSUE THREAD

**Issue by venusafroid** [lixin4ever/TNet#11]
Hi,

When I try to run TNet model, I have error like this:

/home/dm/.theano/compiledir_Linux-4.15--generic-x86_64-with-debian-stretch-sid-x86_64-3.6.9-64/tmp4ejrz036/mod.cpp:19:0: error: narrowing conversion of '138' from 'int' to 'char' inside { } [-Wnarrowing]
/home/dm/.theano/compiledir_Linux-4.15--generic-x86_64-with-debian-stretch-sid-x86_64-3.6.9-64/tmp4ejrz036/mod.cpp:19:0: error: narrowing conversion of '192' from 'int' to 'char' inside { } [-Wnarrowing]
/home/dm/.theano/compiledir_Linux-4.15--generic-x86_64-with-debian-stretch-sid-x86_64-3.6.9-64/tmp4ejrz036/mod.cpp:19:0: error: narrowing conversion of '168' from 'int' to 'char' inside { } [-Wnarrowing]
/home/dm/.theano/compiledir_Linux-4.15--generic-x86_64-with-debian-stretch-sid-x86_64-3.6.9-64/tmp4ejrz036/mod.cpp:19:0: error: narrowing conversion of '168' from 'int' to 'char' inside { } [-Wnarrowing]

Traceback (most recent call last):
  File "main.py", line 59, in <module>
    model = TNet(args=args)
  File "/home/dm/lili/TNet/layer.py", line 336, in __init__
    self.make_function()
  File "/home/dm/lili/TNet/layer.py", line 417, in make_function
    updates=self.updates,
  File "/home/dm/anaconda3/envs/theano0_9_0/lib/python3.6/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/home/dm/anaconda3/envs/theano0_9_0/lib/python3.6/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/dm/anaconda3/envs/theano0_9_0/lib/python3.6/site-packages/theano/compile/function_module.py", line 1795, in orig_function
    defaults)
  File "/home/dm/anaconda3/envs/theano0_9_0/lib/python3.6/site-packages/theano/compile/function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/dm/anaconda3/envs/theano0_9_0/lib/python3.6/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/dm/anaconda3/envs/theano0_9_0/lib/python3.6/site-packages/theano/gof/vm.py", line 1047, in make_all
    impl=impl))
  File "/home/dm/anaconda3/envs/theano0_9_0/lib/python3.6/site-packages/theano/gof/op.py", line 935, in make_thunk
    no_recycling)
  File "/home/dm/anaconda3/envs/theano0_9_0/lib/python3.6/site-packages/theano/gof/op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/dm/anaconda3/envs/theano0_9_0/lib/python3.6/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/home/dm/anaconda3/envs/theano0_9_0/lib/python3.6/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/home/dm/anaconda3/envs/theano0_9_0/lib/python3.6/site-packages/theano/gof/cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/dm/anaconda3/envs/theano0_9_0/lib/python3.6/site-packages/theano/gof/cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/dm/anaconda3/envs/theano0_9_0/lib/python3.6/site-packages/theano/gof/cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "/home/dm/anaconda3/envs/theano0_9_0/lib/python3.6/site-packages/theano/gof/cmodule.py", line 2316, in compile_str
    (status, compile_stderr.replace('\n', '. ')))

I am new to theano. What can I do with this?
Thanks!

**Comment by venusafroid** [comment]
I have solved this problem by creating new environment :)
